version: "3.8"

services:
  crdb:
    container_name: cockroach-db
    image: cockroachdb/cockroach:v19.2.2
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/.docker-volumes/cockroach-data/crdb:/cockroach/cockroach-data"
    networks:
      - web_api

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    container_name: minio-storage
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server --console-address :9001 /data
    volumes:
      - "${PWD}/.docker-volumes/minio/data:/data"
    networks:
      - web_api

  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio-storage:9000 admin admin123;
      /usr/bin/mc rb --force local/2023-rest-api/;
      /usr/bin/mc mb --quiet local/2023-rest-api/;
      /usr/bin/mc policy set public local/2023-rest-api;
      "
    networks:
      - web_api

networks:
  web_api:
    driver: bridge
