version: "3.8"

services:
  crdb-1:
    image: cockroachdb/cockroach:latest
    ports:
      - "8080:8080"
      - "26257:26257"
    volumes:
      - crdb-1-data:/cockroach/cockroach-data
    command: start --insecure --join=crdb-1,crdb-2,crdb-3
    networks:
      - web_api

  crdb-2:
    image: cockroachdb/cockroach:latest
    volumes:
      - crdb-2-data:/cockroach/cockroach-data
    command: start --insecure --join=crdb-1,crdb-2,crdb-3
    networks:
      - web_api

  crdb-3:
    image: cockroachdb/cockroach:latest
    volumes:
      - crdb-3-data:/cockroach/cockroach-data
    command: start --insecure --join=crdb-1,crdb-2,crdb-3
    networks:
      - web_api

  crdb-runner:
    image: cockroachdb/cockroach:latest
    restart: on-failure
    depends_on:
      - crdb-1
      - crdb-2
      - crdb-3
    volumes:
      - ./entrypoints/db/sql-init.d:/docker-entrypoint-initdb.d
      - ./entrypoints/db/init-data.sh:/usr/local/bin/init-data.sh:ro
    command:
      - "shell"
      - "/usr/local/bin/init-data.sh"
      - "crdb-1:26257"
    networks:
      - web_api

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    container_name: minio-storage
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin.123
    command: server --console-address :9001 /data
    volumes:
      - minio-data:/data
    networks:
      - web_api

  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio-storage:9000 admin admin.123;
      /usr/bin/mc rb --force local/2023-rest-api/;
      /usr/bin/mc mb --quiet local/2023-rest-api/;
      /usr/bin/mc policy set public local/2023-rest-api;
      "
    networks:
      - web_api

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./entrypoints/metrics/prometheus:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global
    networks:
      - web_api

  alertmanager:
    image: prom/alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - ./entrypoints/metrics/alertmanager/:/etc/alertmanager/
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    networks:
      - web_api

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    restart: always
    deploy:
      mode: global
    networks:
      - web_api

  grafana:
    image: grafana/grafana
    user: "472"
    restart: always
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./entrypoints/metrics/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./entrypoints/metrics/grafana/config.monitoring
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - web_api

networks:
  web_api:
    driver: bridge
volumes:
  crdb-1-data:
  crdb-2-data:
  crdb-3-data:
  minio-data:
  prometheus-data:
  grafana-data:
