## Register User

@BaseURL=http://localhost:4500/api/v1

PUT {{BaseURL}}/user/update
Content-Type: application/json

{
    "user_id":"4935f9f9-4c44-4eea-b9e8-a217914d01b5",
    "fullname":"Jose E. Martinez",
    "email": "josemartinezchevez@gmail.com"
}