### Update User

@BaseURL=http://localhost:4500/api/v1
@Token=abc

PUT {{BaseURL}}/user/update
Content-Type: application/json
Authorization: Bearer {{Token}}

{
    "fullname":"Jose Elias Martinez",
    "email": "josemartinezchevez@gmail.com",
    "old_password":"testing-pass",
    "new_password":"hola.1234"
}

### Retireve use's information

GET {{BaseURL}}/user/me
Content-Type: application/json
Authorization: Bearer {{Token}}